unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind v split-window -h    # Vertical split
bind s split-window -v    # Horizontal split

# Enable search in copy mode
bind [ copy-mode
bind / command-prompt -p "Search:" "send-keys / '%%'\\n"
bind n send-keys n
bind N send-keys N

# Set the base window to 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Set search to foward slash
bind C-s copy-mode \; send -X search-forward

# Enable mouse scrolling
set -g mouse on

# Vi copy mode
set-window-option -g mode-keys vi
